spring.application.name=urlshortener

spring.datasource.url=jdbc:postgresql://localhost:5432/urlshortener
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

app.url.expiration-days=7
app.short-code.generator=base62

logging.level.com.alanpmz.urlshortener=DEBUG